# Generated by Django 5.0.6 on 2024-05-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='Unknown Author', max_length=200)),
                ('description', models.TextField(default='No description available')),
                ('genres', models.CharField(default='No genres specified', max_length=200)),
                ('ongoing', models.BooleanField(default=True)),
                ('image_file', models.ImageField(blank=True, default=None, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(default='Chapter Title', max_length=200)),
                ('pdf_file', models.FileField(default=None, upload_to='chapters/')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='myapp.manga')),
            ],
        ),
    ]
