# Generated by Django 5.0.6 on 2024-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, default=None, upload_to='chapters/'),
        ),
    ]
